[workspace]
resolver = "3"
members = [
    "crates/ada-a4-entmax-bnb",
    "crates/ada-core",
    "crates/ada-oracle",
    "crates/ada-runner",
]

[workspace.package]
edition = "2024"
rust-version = "1.85"
license = "MIT OR Apache-2.0"

[workspace.lints.rust]
unsafe_code = "forbid"

[workspace.lints.clippy]
all = "warn"
pedantic = "warn"
