[package]
name = "ada-trace"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
ada-implementation = { path = "../ada-implementation" }
ada-semantic = { path = "../ada-semantic" }
ada-workload = { path = "../ada-workload" }

[dev-dependencies]
ada-core = { path = "../ada-core" }

[lints]
workspace = true
