[package]
name = "ada-a2-real-v-trace"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[lints]
workspace = true

[dev-dependencies]
ada-a4-entmax-bnb = { path = "../ada-a4-entmax-bnb" }
ada-a4-qk-box = { path = "../ada-a4-qk-box" }
ada-a5-hierarchical-bounds = { path = "../ada-a5-hierarchical-bounds" }
ada-a5-real-qk-trace = { path = "../ada-a5-real-qk-trace" }
