[package]
name = "ada-cost-model"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
ada-implementation = { path = "../ada-implementation" }
ada-objective = { path = "../ada-objective" }
ada-workload = { path = "../ada-workload" }

[lints]
workspace = true
